version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
      time: "06:30"
      timezone: "Europe/Belfast"
    labels:
      - "Python"
    commit-message:
      prefix: "python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:30"
      timezone: "Europe/Belfast"
    labels:
      - "GitHub Actions"
    commit-message:
      prefix: "actions"
